### ISSUE TITLE
install-dependencies.sh fails on kali linux 2016.1 rolling swig2.0 is not available

### ISSUE THREAD

**Issue by binarymist** [breenmachine/httpscreenshot#20]
cd /opt/httpscreenshot/ && ./install-dependencies.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package swig2.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  swig:i386 swig

E: Package 'swig2.0' has no installation candidate

Recommended approach please?

**Comment by binarymist** [comment]
./httpscreenshot.py -l inputURLs -p -w 5 -a -vH

Produces and html and png file. So appears it's working. Does this mean swit2.0 is not a mandatory requirement or maybe it's still required to run masshttp.sh?

Looks like we have swig3.0 installed in kali linux 2016.1 rolling.

**Comment by breenmachine** [comment]
Swig is needed to draw a png if basic authentication happens, if you have
swig 3 it will likely work. I'll update the dependency script.

Thanks!

**Comment by binarymist** [comment]
I guess update the README.md as well? Cheers.

**Comment by SergKV** [comment]
Hi, the problem is still exists,
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package swig2.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  swig

E: Package 'swig2.0' has no installation candidate

Bcz of the new swig which is installed, 3.0, shows always this failure.
Regard.

**Comment by breenmachine** [comment]
Updated install.sh to use swig3.0.

**Comment by Le0theking** [comment]
It still not working.Every time getting the below error. @breenmachine Can you pls help me with this.
----------------------------------------------------------------------------------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package xvfb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package swig
E: Unable to locate package swig3.0
E: Couldn't find any package by glob 'swig3.0'
E: Couldn't find any package by regex 'swig3.0'
E: Unable to locate package libssl-dev
E: Unable to locate package libjpeg-dev
E: Package 'xvfb' has no installation candidate

**Comment by JMWatkins** [comment]
Hey guys,
I'm having the exact same problem as Le0theking... PLEASE HELP. I know it's probably something obvious but I feel like I've tried everything...
